version: "3.9"
services:
  mentorme-client-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
    # external:internal
      - "8080:80"
